### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by sivkovic**
## Changelog

- #129 Cleanup Directories Refactor

### CODE REVIEW

**Comment by ionox0** [comment]
🎉

**Comment by ionox0** [comment]
Just wondering what would happen if we try to use the restart endpoint for a job that was cleaned up?

**Comment by sivkovic** [comment]
It would run without using cache. You wan't be able to resume it.

**Review by nikhil — APPROVED** [review]
LGTM

**Pull request merged**
